-- insert into User(userId, userName, password, email, reputation, admin) values (1, "Aldo", "buonaquestacadrega", "aldo.baglio@agg.it", -3, false);
-- insert into User(userId, userName, password, email, reputation, admin) values (2, "Giovanni", "franco", "giovanni.storti@agg.it", +5, true);
-- insert into User(userId, userName, password, email, reputation, admin) values (3, "Giacomo", "ilnonno", "giacomo.poretti@agg.it", +1.2, false);
